// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competencies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompetency = `-- name: CreateCompetency :one
INSERT INTO competencies (
    name,
    description
) VALUES (
    $1, $2
) RETURNING id, name, description, created_at, updated_at
`

type CreateCompetencyParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateCompetency(ctx context.Context, arg CreateCompetencyParams) (Competency, error) {
	row := q.db.QueryRow(ctx, createCompetency, arg.Name, arg.Description)
	var i Competency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCompetencies = `-- name: GetAllCompetencies :many
SELECT id, name, description, created_at, updated_at FROM competencies
ORDER BY created_at DESC
`

func (q *Queries) GetAllCompetencies(ctx context.Context) ([]Competency, error) {
	rows, err := q.db.Query(ctx, getAllCompetencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competency
	for rows.Next() {
		var i Competency
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompetencyByID = `-- name: GetCompetencyByID :one
SELECT id, name, description, created_at, updated_at FROM competencies
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompetencyByID(ctx context.Context, id int32) (Competency, error) {
	row := q.db.QueryRow(ctx, getCompetencyByID, id)
	var i Competency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetencyByName = `-- name: GetCompetencyByName :one
SELECT id, name, description, created_at, updated_at FROM competencies
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetCompetencyByName(ctx context.Context, name string) (Competency, error) {
	row := q.db.QueryRow(ctx, getCompetencyByName, name)
	var i Competency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompetencyDescription = `-- name: UpdateCompetencyDescription :one
UPDATE competencies
SET description = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, name, description, created_at, updated_at
`

type UpdateCompetencyDescriptionParams struct {
	Description pgtype.Text `json:"description"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateCompetencyDescription(ctx context.Context, arg UpdateCompetencyDescriptionParams) (Competency, error) {
	row := q.db.QueryRow(ctx, updateCompetencyDescription, arg.Description, arg.ID)
	var i Competency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
